Use Github Actions to run tests
duffelhq/paginator pull request #100
Opened 2021-02-14 19:42 UTC by dolfinus

Just like https://github.com/duffelhq/paginator/pull/90, but instead of CircleCI it's better to use Github Actions (IMHO).
Github Actions supports matrix builds (unlike Circle CI), and also allows to build really impressive CI/CD pipelines and PR/issues automatization.

2021-02-28 23:35 UTC, dolfinus commented
@sgerrand @jbernardo95 @msz What do you think about this PR?

2021-03-01 14:46 UTC, sgerrand requested changes
Thank you for your contribution! These changes look good overall. I've added a few suggestions.

One thing missing is a link to this workflow running successfully. Would you please add this, either in the description or as a comment, to make it easier for other reviewers.

2021-03-01 14:46 UTC, sgerrand commented on .github/workflows/test.yml
> +        mix deps.get
Suggest running these as separate steps. There's little runtime cost to doing so and it makes debugging easier.
```suggestion
    - name: Install hex
      run: mix local.hex --force

    - name: Install rebar
      run: mix local.rebar --force

    - name: Install package dependencies
      run: mix deps.get
```

2021-03-01 14:46 UTC, sgerrand commented on .github/workflows/test.yml
> +        mix test
Again, suggest separating these commands into separate steps.
```suggestion
    - name: Remove compiled application files
      run: mix clean

    - name: Run unit tests
      run: mix test
```

2021-03-01 14:46 UTC, sgerrand commented on .github/workflows/test.yml
> +        mix inch.report
A tiny nitpick here
```suggestion
    - name: Check documentation quality
      run: mix inch.report
```

2021-03-01 14:49 UTC, sgerrand commented
I think one other thing which needs to be done before this can be merged is enabling GitHub Actions on this repository and ensuring that at least 2-3 runs of this workflow complete successfully.

2021-03-01 14:52 UTC, sgerrand commented
> Github Actions supports matrix builds (unlike Circle CI)

Note that CircleCI has [supported matrices in their builds](https://circleci.com/blog/circleci-matrix-jobs/) since April 2020. I only became aware of this myself late last year.

2021-03-01 14:56 UTC, dolfinus commented
Thank your for review!

I've added a link to a successfully executed workflow.

2021-03-01 15:22 UTC, sgerrand approved these changes
LGTM. 👍

2021-03-01 15:23 UTC, merged